apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: my-namespace
data:
  router-mode: interior
  console-user: "admin"
  console-password: "changeme"
  console: "true"
  flow-collector: "true"
