apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
spec:
  channel: stable-2
  installPlanApproval: Automatic
  name: skupper-operator
  source: skupper-operator
  sourceNamespace: openshift-marketplace
  startingCSV: skupper-operator.v2.0.0
